name: Default
version: 1.0.0
description: Default Flextype theme
author:
  name: Sergey Romanenko
  email: awilum@yandex.ru
  url: https://github.com/Awilum
homepage: https://github.com/flextype/flextype
bugs: https://github.com/flextype/flextype/issues
license: MIT

# Theme settings
enabled: true
