#
# Site configuration
#

title: "Flextype"
description: "Modern Open Source Flat-File Content Management System"
author:
  email: ""

timezone: UTC
charset: UTF-8
date_format: "F d Y H:i:s."

theme: default

plugins:
  - highlight
  - component

locale: "en"
locales: [en]

pages:
  main: home

errors:
  display: true

social_link:
  github: "https://github.com/flextype-components"
  vkontakte: "https://vk.com/flextype.components"

cache:
  enabled: true
  prefix: Flextype
  driver: auto
  lifetime: 604800
